name: adcoin
description: AdCoin - 看广告赚游戏币，与经济插件互通，含好友社交
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.2.3
  google_mobile_ads: ^9.1.0
  mobile_scanner: ^7.4.2
  permission_handler: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true